# Generated by Django 3.1.2 on 2023-11-28 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultoMayor',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('fechaNac', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('cupo_maximo', models.PositiveSmallIntegerField(default=15)),
                ('cupo_actual', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoTaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='default_value', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TallerTomado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInscripcion', models.DateTimeField(auto_now_add=True)),
                ('adulto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.adultomayor')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.talleres')),
            ],
        ),
        migrations.AddField(
            model_name='talleres',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.tipotaller'),
        ),
        migrations.CreateModel(
            name='InscripcionTaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.talleres')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.adultomayor')),
            ],
        ),
    ]
