# Generated by Django 3.1.2 on 2023-11-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_talleres_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='talleres',
            name='inscritos',
            field=models.ManyToManyField(related_name='talleres_inscritos', through='talleres.InscripcionTaller', to='talleres.AdultoMayor'),
        ),
    ]
